cache:
    key: "$CI_JOB_NAME"
    untracked: true
    paths:
    - $HOME/.cargo/
    - target/
    
.cargo_test_template: &cargo_test
  script:
  - rustc --version && cargo --version
  - cargo build
  - cargo test --verbose

test:stable:
  image: "rust:latest"
  <<: *cargo_test


# Always want to run rustfmt and clippy against our tests, to ensure that
# we aren't using any anti-patterns or failing to follow our style guide
lint:rustfmt:
  image: "guangie88/rustfmt-clippy:stable"
  script:
    - cargo fmt -- --check

lint:clippy:
  image: "guangie88/rustfmt-clippy:stable"
  script:
    - cargo clippy -- -D warnings # Turn all warnings into errors
