[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.build-release]
command = "cargo"
args = ["build","--release"]

[tasks.copy-lib]
command = "cp"
args = ["target/debug/liblexibook.a","../macos/Lexibook/lib/"]
dependencies = ["build"]

[tasks.copy-lib-release]
command = "cp"
args = ["target/release/liblexibook.a","../macos/Lexibook/lib/"]
dependencies = ["build-release"]

[tasks.copy-header]
command = "cp"
args = ["lexibook.h","../Mac/include/"]

[tasks.dev]
dependencies = ["format", "test", "build", "copy-lib", "copy-header"]

[tasks.release]
dependencies = ["format", "test", "build-release", "copy-lib-release", "copy-header"]
