consolidate-commits = true
disable-publish = true
no-dev-version = true
pre-release-commit-message = "[skip ci]\nRelease {{version}}"
tag-message = "{{prefix}}v{{version}}"
tag-name = "{{prefix}}v{{version}}"
pre-release-replacements = [
  {file="README.md", search="Current release: [a-z0-9\\.-]+", replace="Current release: {{version}}"} ,
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}"},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate"},
]
