name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: rustfmt, clippy
          override: true
    - name: Run tests
      run: |
        cargo +nightly fmt -- --check
        cargo +nightly clippy --all-features -- -D warnings
        cargo test 
      working-directory: rust
    - name: Build
      run: cargo build --verbose
      working-directory: rust
